# Generated by Django 5.2.7 on 2025-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('proyector', 'Proyector'), ('notebook', 'Notebook'), ('impresora', 'Impresora')], default='')),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('en_reparacion', 'En Reparación'), ('dado_de_baja', 'Dado de Baja')], default='operativo')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
    ]
